# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [42]:
import numpy as np

2. Create a null vector of size 10 

In [43]:
# arr1 = np.zeros(10)   : We can use this definition if we want to consider zeros as null values
arr1 =  np.empty(10)
arr1 [:] = np.NaN       # if we want to consider not a number as a null value then we can use this expression
arr1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

3. Create a vector with values ranging from 10 to 49

In [44]:
arr2 = np.arange(10,50)

4. Find the shape of previous array in question 3

In [45]:
arr2.shape

(40,)

5. Print the type of the previous array in question 3

In [46]:
arr2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [47]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [48]:
arr2.ndim

1

8. Create a boolean array with all the True values

In [49]:
#arr_bool = np.array([True, True, True, True])   : another way

arr_bool = np.ones((10), dtype = bool)   # np.full((5), True)  : another way
arr_bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [50]:
# another way of creating 2 Dimensional array:  two_dim_arr = np.arange(15).reshape(3,5)   
two_dim_arr = np.array([[1,2,3,4],[5,6,7,8]])
two_dim_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

10. Create a three dimensional array



In [51]:
three_dim_arr = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])
#another way of creating 3 Dimensional array:  three_dim_arr = np.arange(16).reshape(2,2,4) 
three_dim_arr

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [52]:
arr1 = np.array([1,2,3,4])
reverse_arr =arr1[::-1]
reverse_arr

array([4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [53]:
arr1 = (np.arange(10) == 4).astype(int)
arr1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [54]:
id_mtx = np.identity(3)
#another way is: id_mtx = np.eye(3)
id_mtx

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [55]:
arr = (np.array([1, 2, 3, 4, 5])).astype(float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [56]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2                   # or we can use multiplication function: np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [57]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

# arr3 = np.where(arr1 < arr2, arr2, arr1)   : we can get 3rd array of numbers, this way

arr3 = arr1 == arr2      # We'll get a boolean array also we can also have an array by comparing less than or greater than too
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [58]:
arr = np.arange(10)

arr[1::2]     # arr[arr%2 == 1]     :the same effect could be achieved with this boolean expression

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [59]:
arr[arr%2 == 1] = -1   # arr[1::2] = -1  : another way with same result
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [60]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [61]:
arr = np.ones((5,5))
arr
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [62]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [63]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64   # if we want to have value of 64 on first array of first depth then we can do as: arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [64]:
#arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])  : another way of creating above mentioned array
arr2d = np.arange(9).reshape(3,3)
print(arr2d)
arr_slice = arr2d[0]
arr_slice

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [65]:
# arr2d = np.arange(9).reshape(3,3)  : another way of creating above mentioned array
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr2d)
arr_slice = arr2d[1,1]
arr_slice

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [66]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_slice = arr2d[0:2,2:]
arr_slice

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [67]:
np.random.seed(0)
arr1 = np.random.randn(10,10)  

# Given 10x10 random values can also be generated as: arr1 = np.random.random(100).reshape(10,10)

arr1, np.min(arr1), np.max(arr1)

(array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
         -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
        [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
          0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
        [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
         -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
        [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
          0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
        [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
         -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028],
        [-0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
          0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117],
        [-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
         -0.40178094, -1.6301983

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [69]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a,b) == True)        # alternative ways: np.flatnonzero(np.isin(a, b)) or np.where(np.isin(a,b) == True)


(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
np.random.seed(0)
data = np.random.randn(7, 4)
data, data[names != 'Will']

(array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
        [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
        [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
        [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
        [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
        [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]]),
 array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
        [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
        [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
        [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]]))

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
np.random.seed(0)
data = np.random.randn(7, 4)

# one way could be as: data[names == 'Bob']
print(data)
data[(names != 'Will') & (names != 'Joe')]   # another way could be: data[~((names == 'Will') | (names == 'Joe'))]


[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852 -0.18718385]]


array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [87]:
arr = np.arange(1,16).reshape((5,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [88]:
arr = np.arange(1,17).reshape((2,2,4))
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [91]:
arr.swapaxes(1, 2)   # another way is:  arr.transpose((1,0,2))

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [78]:
arr = np.array([.1, 1, 0.2, 0, .5, .15, 12, 16, 9, 10])
#arr = np.sqrt(arr)
#arr[arr < 0.5] = 0
# above two statements would also work fine. Below statement is another way of doing the same.
print("Square roots are: ", np.sqrt(arr))
np.where(np.sqrt(arr) < 0.5, 0, np.sqrt(arr))  # values less than 0.5 are replaced with 0

Square roots are:  [0.31622777 1.         0.4472136  0.         0.70710678 0.38729833
 3.46410162 4.         3.         3.16227766]


array([0.        , 1.        , 0.        , 0.        , 0.70710678,
       0.        , 3.46410162, 4.        , 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [85]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
#arr3 = np.where(arr1 > arr2, arr1, arr2) : This is another way of getting 3rd array with max values of first 2 arrays
arr3 = np.maximum(arr1,arr2)
# we can display all the three arrays and observe that 3rd array carries the max values of first 2 arrays
print(arr1)
print(arr2)
arr3

[ 0.8957173   0.80524403 -1.20641178  2.56564595  1.43125599  1.34030885
 -1.1702988  -0.22616928  0.41083451  0.81385029  0.13200317 -0.82731694]
[-0.07646702 -1.18767758  1.1301273  -1.43673732 -1.41368087  1.60792047
  1.02418016  0.56960526  0.8759064  -2.21137223  0.97446607 -2.00674721]


array([ 0.8957173 ,  0.80524403,  1.1301273 ,  2.56564595,  1.43125599,
        1.60792047,  1.02418016,  0.56960526,  0.8759064 ,  0.81385029,
        0.97446607, -0.82731694])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [84]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)  # unique() returns sorted unique values in an array

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [82]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b) # another way could be as: a[~(np.isin(a,b))]


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1] = newColumn   # we are not taking index no. as column no. So column index 1 is column no. 2
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

x @ y  # We could also perfom dot matrix product as: np.dot(x,y)  Or  x.dot(y)


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
np.random.seed(12345)
arr = np.random.random(20)
print(arr)
arr.cumsum()

[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503 0.5955447
 0.96451452 0.6531771  0.74890664 0.65356987 0.74771481 0.96130674
 0.0083883  0.10644438 0.29870371 0.65641118 0.80981255 0.87217591
 0.9646476  0.72368535]


array([ 0.92961609,  1.24599165,  1.42991046,  1.63447074,  2.20219577,
        2.79774047,  3.76225499,  4.41543209,  5.16433872,  5.81790859,
        6.5656234 ,  7.52693014,  7.53531844,  7.64176281,  7.94046653,
        8.59687771,  9.40669026, 10.27886618, 11.24351378, 11.96719912])