# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
import numpy as np

In [25]:
arr = np.arange(10)
arr2 = arr.reshape((2,5))
# in a single statement we can do it as arr2 = np.arange(10).reshape((2,5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [26]:
arr1 = np.array([[0, 1, 2, 3, 4],  # arr1 can be generated as: arr1 = np.arange(10).reshape(2,5)
        [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],  # arr2 can be generated as: arr2 = np.ones(10).reshape(2,5).astype(int)
       [1, 1, 1, 1, 1]])
np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [27]:
# we can also use arrays from Question 2

a = np.arange(10).reshape((2,5))
b = np.ones(10).reshape((2,5)).astype(int)
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [28]:
arr = np.arange(10).reshape((2,5,1)) # we can use 2D array as well: arr = np.arange(10).reshape((2,5))
print(arr)
arr.flatten()


[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [22]:
arr1 = np.arange(15).reshape((3,5))
print(arr1)               # This expression gives  1 x D array:  arr1.reshape(-1)
arr1.ravel()             # or if array is multidimensional we could use: arr1.base 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [52]:
arr2 = np.arange(15)
arr2.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [53]:
arr1 = np.arange(2,27).reshape((5,5))
print(arr1)
print(np.square(arr1))   # we can also compute square without square function as: arr1 = arr1 ** 2

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]
[[  4   9  16  25  36]
 [ 49  64  81 100 121]
 [144 169 196 225 256]
 [289 324 361 400 441]
 [484 529 576 625 676]]


## Question:8

### Create 5x6 an array and find the mean?

In [54]:
np.random.seed(123456)
arr_m = np.random.randn(5,6)
print(arr_m)
print(np.mean(arr_m))   # We can also use array instance method as: arr_m.mean()
print("Mean along axis 0: ",arr_m.mean(axis=0))
print("Mean along axis 1: ",arr_m.mean(axis=1))


[[ 0.4691123  -0.28286334 -1.5090585  -1.13563237  1.21211203 -0.17321465]
 [ 0.11920871 -1.04423597 -0.86184896 -2.10456922 -0.49492927  1.07180381]
 [ 0.72155516 -0.70677113 -1.03957499  0.27185989 -0.42497233  0.56702035]
 [ 0.27623202 -1.08740069 -0.67368971  0.11364841 -1.47842655  0.52498767]
 [ 0.40470522  0.57704599 -1.71500202 -1.03926848 -0.37064686 -1.15789225]]
-0.3656901919163959
Mean along axis 0:  [ 0.39816268 -0.50884503 -1.15983484 -0.77879236 -0.3113726   0.16654098]
Mean along axis 1:  [-0.23659076 -0.55242848 -0.10181384 -0.38744148 -0.5501764 ]


## Question:9

### Find the standard deviation of the previous array in Q8?

In [55]:
np.std(arr_m)       # another way is: arr_m.std()

0.8541007331121984

## Question:10

### Find the median of the previous array in Q8?

In [56]:
np.median(arr_m)

-0.39780959401264193

## Question:11

### Find the transpose of the previous array in Q8?

In [57]:
arr_m.T              # we can also find transpose as: arr_m.transpose()

array([[ 0.4691123 ,  0.11920871,  0.72155516,  0.27623202,  0.40470522],
       [-0.28286334, -1.04423597, -0.70677113, -1.08740069,  0.57704599],
       [-1.5090585 , -0.86184896, -1.03957499, -0.67368971, -1.71500202],
       [-1.13563237, -2.10456922,  0.27185989,  0.11364841, -1.03926848],
       [ 1.21211203, -0.49492927, -0.42497233, -1.47842655, -0.37064686],
       [-0.17321465,  1.07180381,  0.56702035,  0.52498767, -1.15789225]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [58]:
arr = np.arange(1,17).reshape((4,4))
print(arr)
np.sum(np.diag(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


34

## Question:13

### Find the determinant of the previous array in Q12?

In [59]:
from numpy.linalg import det

In [60]:
det(arr)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [61]:
arr = np.arange(1,50)
print("5th percentile: ", np.percentile(arr, 5))
print("95th percentile: ", np.percentile(arr, 95))

5th percentile:  3.4000000000000004
95th percentile:  46.599999999999994


## Question:15

### How to find if a given array has any null values?

In [62]:
arr = np.array([[4, 43, 101, 0, 13,np.nan, 40, 61], [3, np.nan, 4, 45, np.nan, 0, 43, np.nan]])
print(np.isnan(arr))  # True for null values
np.argwhere(np.isnan(arr)) # Another way of finding null values with indices

[[False False False False False  True False False]
 [False  True False False  True False False  True]]


array([[0, 5],
       [1, 1],
       [1, 4],
       [1, 7]], dtype=int64)