# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr2 = arr.reshape((2,5))
# in a single statement we can do it as arr2 = np.arange(10).reshape((2,5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
arr1 = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
# we can also use arrays from Question 2

a = np.arange(10).reshape((2,5))
b = np.ones(10).reshape((2,5)).astype(int)
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
arr = np.arange(10).reshape((2,5,1)) # we can use 2D array as well: arr = np.arange(10).reshape((2,5))
# print(arr)
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
arr1 = np.arange(15).reshape((3,5))
# print(arr1)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
arr2 = np.arange(15)
arr2.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr1 = np.arange(2,27).reshape((5,5))
print(arr1)
print(np.square(arr1))   # we can also compute square without square function as: arr1 = arr1 ** 2

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]
[[  4   9  16  25  36]
 [ 49  64  81 100 121]
 [144 169 196 225 256]
 [289 324 361 400 441]
 [484 529 576 625 676]]


## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr_m = np.random.randn(5,6)
print(arr_m)
print(np.mean(arr_m))   # We can also use array instance method as: arr_m.mean()
print("Mean along axis 0: ",arr_m.mean(axis=0))
print("Mean along axis 1: ",arr_m.mean(axis=1))


[[ 2.69923243  0.88194692 -0.95694376  0.63706199  1.13155561 -1.17702271]
 [ 0.34156334  1.81801313 -0.80195967 -1.13320666  0.02181559  0.51956905]
 [ 0.28316732  0.31437587 -1.01967521 -0.42960102  1.35153041  0.43411484]
 [-0.40642182 -1.55166587  0.06326699  0.84255458 -0.89515896 -0.53192007]
 [-0.60031886 -0.77404036 -0.65496478  0.1426446  -0.7802528  -0.31307977]]
-0.018127321738005152
Mean along axis 0:  [ 0.46344448  0.13772594 -0.67405529  0.0118907   0.16589797 -0.21366773]
Mean along axis 1:  [ 0.53597175  0.12763246  0.15565204 -0.41322419 -0.49666866]


## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
print(np.std(arr_m))
arr_m.std()

0.9585724877976856


0.9585724877976856

## Question:10

### Find the median of the previous array in Q8?

In [11]:
np.median(arr_m)

-0.14563208946394438

## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
arr_m.T              # we can also find transpose as: arr_m.transpose()

array([[ 2.69923243,  0.34156334,  0.28316732, -0.40642182, -0.60031886],
       [ 0.88194692,  1.81801313,  0.31437587, -1.55166587, -0.77404036],
       [-0.95694376, -0.80195967, -1.01967521,  0.06326699, -0.65496478],
       [ 0.63706199, -1.13320666, -0.42960102,  0.84255458,  0.1426446 ],
       [ 1.13155561,  0.02181559,  1.35153041, -0.89515896, -0.7802528 ],
       [-1.17702271,  0.51956905,  0.43411484, -0.53192007, -0.31307977]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
arr = np.arange(1,17).reshape((4,4))
print(arr)
np.sum(np.diag(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


34

## Question:13

### Find the determinant of the previous array in Q12?

In [14]:
from numpy.linalg import det

In [15]:
det(arr)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [16]:
arr = np.arange(1,11)
print("5th percentile: ", np.percentile(arr, 5))
print("95th percentile: ", np.percentile(arr, 95))

5th percentile:  1.4500000000000002
95th percentile:  9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [18]:
arr = np.array([[4, 43, 101, 0, 13,np.nan, 40, 61], [3, np.nan, 4, 45, np.nan, 0, 43, np.nan]])
print(np.isnan(arr))  # True for null values
np.argwhere(np.isnan(arr)) # Another way of finding null values with indices.

[[False False False False False  True False False]
 [False  True False False  True False False  True]]


array([[0, 5],
       [1, 1],
       [1, 4],
       [1, 7]], dtype=int64)